### ISSUE TITLE
Navigation between bottomsheet and composable issue

### ISSUE THREAD

**Issue by mimai-hen** [stefanoq21/BottomSheetNavigator3#6]
Hi,
I'm facing a regression since I've migrated from 0.0.5 to 0.0.6 version

In version 0.0.5 I navigate from composable A to bottomsheet B, then navigate directly from bottomsheet B to composable C. 
C is well displayed and when user press back, it navigates back to composable A

In version 0.06 I navigate from composable A to bottomsheet B, then navigate directly from bottomsheet B to composable C. 
C is quickly displayed and disappear, application navigates back to composable A without any action from user.

May be when bottomsheet is dismissed the lib forces to navigate back to previous composable ? Or may be I misunderstood something ?
I had to downgrade to 0.0.5 version :-/

Can you double check this issue ? Thanks

**Comment by stefanoq21** [comment]
Hi thanks for your message. I will check it as soon as possible and let you know

**Comment by stefanoq21** [comment]
Hi @mimai-hen, 
I've reviewed the code and you're absolutely right. I apologize for the delay, I was on vacation.
Thank you for identifying this issue. I'll prioritize fixing it and include the solution in the upcoming version. 
I'll keep you updated on the progress.

**Comment by mimai-hen** [comment]
Many thanks !

**Comment by mimai-hen** [comment]
I confirm it is fixed in 0.0.7 :-)
Thank you for your responsiveness !
